name: Release

on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:

  dist:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: luau-lsp-win64
            code-target: [win32-x64, win32-arm64]
          - os: ubuntu-20.04
            artifact-name: luau-lsp-linux
            code-target: [linux-x64]
          - os: ubuntu-20.04
            artifact-name: luau-lsp-linux-arm64
            code-target: [linux-arm64]
          - os: macos-latest
            artifact-name: luau-lsp-macos
            code-target: [darwin-x64, darwin-arm64]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Server
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DLSP_STATIC_CRT:BOOL=ON
          cmake --build . --config Release --target Luau.LanguageServer.CLI -j 3

      - name: (MacOS) Verify universal build
        if: matrix.os == 'macos-latest'
        run: lipo -archs build/luau-lsp

      - name: Copy Build into Extension
        shell: bash
        run: |
          mkdir -p ./dist
          mkdir -p editors/code/bin
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp BUILD_/Release/luau-lsp.exe editors/code/bin/server.exe
          else
            cp BUILD_/luau-lsp editors/code/bin/server
            chmod 777 editors/code/bin/server
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.artifact-name }}
          path: ./dist

      - name: Upload Server to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./dist/server.zip
          asset_name: ${{ matrix.artifact-name }}.zip
          asset_content_type: application/octet-stream

      - run: npm ci
        working-directory: editors/code

      - name: Publish Extension
        working-directory: editors/code
        run: npx @vscode/vsce publish --pat ${{ secrets.MARKETPLACE_TOKEN }} --target ${{ join(matrix.code-target, ' ') }}
